"use client";

// Generated by node scripts/generate-navbar-data.mjs; do not edit.
import React, { type ComponentPropsWithoutRef } from "react";
import { SHARED_NAVBAR, type NavbarVariant } from "@/data/shared-navbar";
import { useSound } from "@/components/SoundProvider";
import InternalNavigationLink from "@/components/app-router/InternalNavigationLink";

export type CanonicalNavbarProps = Omit<ComponentPropsWithoutRef<"header">, "children"> & {
  variant: NavbarVariant;
};

// Structure remains canonical; sound behavior is supplied by the staged provider.
// The brand image and text are structured data rendered as ordinary React elements.
export default function CanonicalNavbar({ variant, ...rootProps }: CanonicalNavbarProps) {
  const navbar = SHARED_NAVBAR[variant];
  const { soundEnabled, toggleSound } = useSound();
  return (
    <header className={"navbar_wrap"} {...rootProps}>
      <div className={"navbar_contain u-grid-custom"}>
        <div id={"w-node-_5e405748-8057-a8c6-6d90-a619b529a5fe-b529a5fc"} className={"navbar_left_contain"}>
          <InternalNavigationLink href={navbar.homeHref} navigationHref={variant === "home" ? "/" : undefined} aria-label={"Return to home"} id={"w-node-_5e405748-8057-a8c6-6d90-a619b529a5ff-b529a5fc"} className={"navbar_home w-inline-block"}>
            <img src={navbar.brand.image.src} alt={navbar.brand.image.alt} className={navbar.brand.image.className} style={navbar.brand.image.style} />
            <span className={navbar.brand.text.className} style={navbar.brand.text.style}>
              {navbar.brand.text.content}
            </span>
          </InternalNavigationLink>
        </div>
        <nav id={"w-node-_5e405748-8057-a8c6-6d90-a619b529a60b-b529a5fc"} className={"navbar_links u-text-style-small u-text-trim-off"}>
          <ul className={"navbar_links_ul u-gap-small u-hflex-left-center"}>
            <li className={"navbar_links_li"}>
              <button id={""} data-open-modal={""} data-link-hover={""} className={"navbar_link"}>
                <div className={"footer_nav_span u-text-style-main is-soon"}>
                  {navbar.aboutSoon}
                </div>
                <div className={"footer_nav_span u-text-style-main"}>
                  {"About"}
                </div>
              </button>
            </li>
            <li data-wf--navbar-links--variant={"base"} className={"navbar_links_li"}>
              <InternalNavigationLink href={"/work"} data-link-hover={""} className={navbar.workClassName} aria-current={navbar.workAriaCurrent ?? undefined}>
                <div className={"footer_nav_span u-text-style-main"}>
                  {"Work"}
                </div>
                <div className={"footer_nav_span u-text-style-main is-soon"}>
                  {"(SOON)"}
                </div>
              </InternalNavigationLink>
            </li>
            <li data-wf--navbar-links--variant={"base"} className={"navbar_links_li"}>
              <InternalNavigationLink href={navbar.servicesHref} navigationHref={"/#services"} data-link-hover={""} className={"navbar_link w-inline-block"}>
                <div className={"footer_nav_span u-text-style-main"}>
                  {"Services"}
                </div>
                <div className={"footer_nav_span u-text-style-main is-soon"}>
                  {"(SOON)"}
                </div>
              </InternalNavigationLink>
            </li>
            <li data-wf--navbar-links--variant={"base"} className={"navbar_links_li"}>
              <InternalNavigationLink href={navbar.processHref} navigationHref={"/#process"} data-link-hover={""} className={"navbar_link w-inline-block"}>
                <div className={"footer_nav_span u-text-style-main"}>
                  {"Process"}
                </div>
                <div className={"footer_nav_span u-text-style-main is-soon"}>
                  {"(SOON)"}
                </div>
              </InternalNavigationLink>
            </li>
          </ul>
        </nav>
        <div id={"w-node-_5e405748-8057-a8c6-6d90-a619b529a618-b529a5fc"} className={"navbar_cta_wrap u-text-style-small u-text-trim-off"}>
          <div className={"navbar_left_sound_wrap"}>
            <button data-btn-default={""} aria-label={"Toggle sound"} aria-pressed={soundEnabled} onClick={toggleSound} className={"navbar_left_sound_btn"}>
              <span className={"navbar_left_sound_container"}>
                <svg xmlns={"http://www.w3.org/2000/svg"} width={"100%"} viewBox={"0 0 26 26"} fill={"none"} className={"navbar_left_sound_on"}>
                  <path d={"M17 10.002C17.6491 10.8674 18 11.9201 18 13.002C18 14.0838 17.6491 15.1365 17 16.002"} stroke={"currentColor"} strokeWidth={"2"} strokeLinecap={"round"} strokeLinejoin={"round"} className={"navbar_path_curve"} />
                  <path d={"M20.364 6.63794C21.1998 7.47367 21.8627 8.46583 22.315 9.55776C22.7673 10.6497 23.0001 11.82 23.0001 13.0019C23.0001 14.1838 22.7673 15.3542 22.315 16.4461C21.8627 17.5381 21.1998 18.5302 20.364 19.3659"} stroke={"currentColor"} strokeWidth={"2"} strokeLinecap={"round"} strokeLinejoin={"round"} className={"navbar_path_curve"} />
                  <path d={"M23 10.002L17 16.002"} stroke={"currentColor"} strokeWidth={"2"} strokeLinecap={"round"} strokeLinejoin={"round"} className={"navbar_path_cross"} />
                  <path d={"M17 10.002L23 16.002"} stroke={"currentColor"} strokeWidth={"2"} strokeLinecap={"round"} strokeLinejoin={"round"} className={"navbar_path_cross"} />
                  <path d={"M12 5.70398C11.9998 5.56469 11.9583 5.42859 11.8809 5.31284C11.8034 5.19709 11.6934 5.10688 11.5647 5.05361C11.436 5.00033 11.2944 4.98637 11.1577 5.01349C11.0211 5.04061 10.8956 5.10759 10.797 5.20598L7.413 8.58898C7.2824 8.72036 7.12703 8.82451 6.95589 8.89541C6.78475 8.9663 6.60124 9.00252 6.416 9.00198H4C3.73478 9.00198 3.48043 9.10734 3.29289 9.29487C3.10536 9.48241 3 9.73676 3 10.002V16.002C3 16.2672 3.10536 16.5216 3.29289 16.7091C3.48043 16.8966 3.73478 17.002 4 17.002H6.416C6.60124 17.0014 6.78475 17.0377 6.95589 17.1086C7.12703 17.1795 7.2824 17.2836 7.413 17.415L10.796 20.799C10.8946 20.8978 11.0203 20.9651 11.1572 20.9924C11.2941 21.0196 11.436 21.0057 11.5649 20.9522C11.6939 20.8988 11.804 20.8083 11.8815 20.6922C11.959 20.5761 12.0002 20.4396 12 20.3V5.70398Z"} stroke={"currentColor"} strokeWidth={"2"} strokeLinecap={"round"} strokeLinejoin={"round"} />
                </svg>
              </span>
            </button>
          </div>
          <div className={"navbar_cta_contain"}>
            <a data-btn-default={""} data-wf--global-button-main--variant={"base"} href={"https://wa.me/6281285313084?text=Hi%20Fadel%2C%20I%27d%20like%20to%20start%20a%20project"} target={"_blank"} className={"g_btn_main w-inline-block"}>
              <div className={"g_btn_text_contain"}>
                <div className={"g_btn_text u-text-style-small u-text-trim-off"}>
                  {"Start a project"}
                </div>
              </div>
              <div className={"g_btn_aside_wrap"}>
                <div className={"g_btn_aside_bg"} />
                <svg xmlns={"http://www.w3.org/2000/svg"} width={"100%"} viewBox={"0 0 12 12"} fill={"none"} className={"g_btn_svg"}>
                  <path d={"M8.90954 9.09046L9 3L2.90954 3.09046L2.90213 4.32367L6.86437 4.25391L2.55914 8.55914L3.44086 9.44086L7.74609 5.13563L7.68708 9.10862L8.90954 9.09046Z"} fill={"currentColor"} />
                </svg>
                <svg xmlns={"http://www.w3.org/2000/svg"} width={"100%"} viewBox={"0 0 12 12"} fill={"none"} className={"g_btn_svg is-absolute"}>
                  <path d={"M8.90954 9.09046L9 3L2.90954 3.09046L2.90213 4.32367L6.86437 4.25391L2.55914 8.55914L3.44086 9.44086L7.74609 5.13563L7.68708 9.10862L8.90954 9.09046Z"} fill={"currentColor"} />
                </svg>
              </div>
            </a>
          </div>
          <button data-menu-btn={""} className={"navbar_menu_btn"}>
            <span className={"navbar_menu_span-wrap"}>
              <span className={"navbar_menu_span"}>
                {"Menu"}
              </span>
              <span className={"navbar_menu_span is-close"}>
                {"Close"}
              </span>
            </span>
          </button>
        </div>
      </div>
    </header>
  );
}
