// Generated by node scripts/generate-cursor-data.mjs; do not edit.
import React, { type ComponentPropsWithoutRef } from "react";
import { type CursorVariant } from "@/data/shared-cursor";
import CanonicalCursorController from "@/components/shared/CanonicalCursorController";

export type CanonicalCursorProps = Omit<ComponentPropsWithoutRef<"div">, "children" | "dangerouslySetInnerHTML"> & {
  variant: CursorVariant;
};

export default function CanonicalCursor({ variant, ...rootProps }: CanonicalCursorProps) {
  return (
    <>
      <div
        data-cursor={""}
        data-cursor-behavior={process.env.NEXT_PUBLIC_CURSOR_MODULAR === '1' ? 'modular' : undefined}
        className={"cursor_wrap"}
        {...rootProps}
      >
        <div className={"cursor-bubble"}>
          <span data-cursor-text-target={""} className={"cursor-bubble__text u-text-style-main"}>
            {"Hello world"}
          </span>
        </div>
        <div className={"cursor_css w-embed"}>
          <style />
        </div>
      </div>
      {process.env.NEXT_PUBLIC_CURSOR_MODULAR === '1' ? <CanonicalCursorController /> : null}
    </>
  );
}
