// Generated by node scripts/generate-about-data.mjs; do not edit.
import React, { type ComponentPropsWithoutRef } from "react";
import { ABOUT_BRAILLE_PATHS, SHARED_ABOUT, type AboutVariant } from "@/data/shared-about";

export type SharedAboutModalProps = Omit<ComponentPropsWithoutRef<"div">, "children"> & {
  variant: AboutVariant;
};

// Markup only: legacy Xe() remains the sole state, focus, scroll-lock, Lenis, animation and lifecycle owner.
// Route-exact style text and static braille paths are rendered as structured React children.
export default function SharedAboutModal({ variant, ...rootProps }: SharedAboutModalProps) {
  const about = SHARED_ABOUT[variant];
  return (
    <div className={"about_wrap"} {...rootProps}>
      <div className={"code-embed-2 w-embed"}>
        <style>{about.css}</style>
      </div>
      <button data-close-modal={""} id={""} className={"about_overlay_close"}>
        <span className={"about_overlay_text u-sr-only"}>
          {"Close about modal"}
        </span>
      </button>
      <div className={"about_modal_wrap"}>
        <button id={""} data-close-modal={""} data-btn-default={""} className={"g_btn_wrapper"}>
          <span data-btn-default={""} id={""} className={"g_btn_main is-close"}>
            <div className={"g_btn_text_contain"}>
              <div className={"g_btn_text u-text-style-small u-text-trim-off is-about"}>
                {"Close"}
              </div>
            </div>
            <div className={"g_btn_aside_wrap"}>
              <div className={"g_btn_aside_bg"} />
              <span className={"g_btn_svg u-text-mono"}>
                {"esc"}
              </span>
              <span className={"g_btn_svg is-absolute u-text-mono"}>
                {"esc"}
              </span>
            </div>
          </span>
        </button>
        <div className={"about_modal_contain"}>
          <div className={"about_modal_top"}>
            <div className={"g_eyebrow_about"}>
              <div className={"g_eyebrow_circle"} />
              <div id={"w-node-_269d15e3-bea6-e335-54d1-1b62770afd60-a51e8985"} className={"g_eyebrow_text u-text-style-large is-about"}>
                {"About the studio"}
              </div>
            </div>
          </div>
          <div className={"about_modal_content"}>
            <p data-split-reveal={"lines"} data-split={"heading"} className={"about_modal_p u-text-style-h5"}>
              {"Hey I'm Fadel Febrian Alexander. I started ARXENOVA because I watched exceptional founders stay invisible because their presence never caught up to who they'd become despite the scale of their ambition."}
              <br />
              <br />
              {"That gap became an obsession. I've spent years breaking down what separates forgettable digital presence from work that actually moves people, thinking that's reached over 60,000 creatives and shapes every project we take on."}
              <br />
              <br />
              {"When we work with founders, we are immersed in your story, ruthless about what moves people, and built to close the gap between who you are and how the world sees you."}
            </p>
            <div className={"about_modal_cover"}>
              <div className={"about_modal_deco_braille"}>
                <div className={"about_modal_deco_braille"}>
                  <svg xmlns={"http://www.w3.org/2000/svg"} width={"100%"} viewBox={"0 0 29 11"} fill={"none"} className={"about_modal_braille"}>
                    {ABOUT_BRAILLE_PATHS.map(path => <path key={path.d} {...path} />)}
                  </svg>
                </div>
                <div className={"about_modal_deco_text u-text-mono"}>
                  {"EST 2022"}
                </div>
                <div className={"about_modal_deco_text u-text-mono"}>
                  {"BASED IN JAKARTA & CILEGON"}
                </div>
              </div>
              <div className={"about_modal_video_wrap"}>
                <video src={""} loop={true} muted={true} playsInline={true} autoPlay={true} className={"about_modal_video u-background-skeleton about-modal-video"} />
                <div className={"about_modal_overlay"} />
                <div className={"about_modal_text u-text-style-h2"}>
                  {"listen"}
                </div>
                <div className={"about_modal_text u-text-style-h2 is-1"}>
                  {"create"}
                </div>
                <div className={"about_modal_text u-text-style-h2 is-2"}>
                  {"obsess"}
                </div>
                <div className={"about_modal_text u-text-style-h2 is-3"}>
                  {"inspire"}
                </div>
              </div>
            </div>
          </div>
          <div className={"about_modal_clients"}>
            <div className={"about_modal_circle"}>
              <div className={"g_eyebrow_circle"} />
              <h2 className={"about_modal_heading u-text-style-h5"}>
                {"Clients"}
              </h2>
            </div>
            <div className={"about_clients_collection w-dyn-list"}>
              <div role={"list"} className={"about_clients_list w-dyn-items"}>
                <div role={"listitem"} className={"about_clients_item w-dyn-item"}>
                  <h2 className={"about_modal_heading u-text-style-h5"}>
                    {"Vinamilk"}
                  </h2>
                </div>
                <div role={"listitem"} className={"about_clients_item w-dyn-item"}>
                  <h2 className={"about_modal_heading u-text-style-h5"}>
                    {"Moc Chau Creamery"}
                  </h2>
                </div>
                <div role={"listitem"} className={"about_clients_item w-dyn-item"}>
                  <h2 className={"about_modal_heading u-text-style-h5"}>
                    {"OH Architecture"}
                  </h2>
                </div>
                <div role={"listitem"} className={"about_clients_item w-dyn-item"}>
                  <h2 className={"about_modal_heading u-text-style-h5"}>
                    {"Supersolid Agency"}
                  </h2>
                </div>
                <div role={"listitem"} className={"about_clients_item w-dyn-item"}>
                  <h2 className={"about_modal_heading u-text-style-h5"}>
                    {"Mammoth Murals"}
                  </h2>
                </div>
                <div role={"listitem"} className={"about_clients_item w-dyn-item"}>
                  <h2 className={"about_modal_heading u-text-style-h5"}>
                    {"SLIK Agency"}
                  </h2>
                </div>
                <div role={"listitem"} className={"about_clients_item w-dyn-item"}>
                  <h2 className={"about_modal_heading u-text-style-h5"}>
                    {"BlueBrown Partners"}
                  </h2>
                </div>
                <div role={"listitem"} className={"about_clients_item w-dyn-item"}>
                  <h2 className={"about_modal_heading u-text-style-h5"}>
                    {"Backhouse"}
                  </h2>
                </div>
                <div role={"listitem"} className={"about_clients_item w-dyn-item"}>
                  <h2 className={"about_modal_heading u-text-style-h5"}>
                    {"University of Sydney"}
                  </h2>
                </div>
              </div>
            </div>
          </div>
          <div className={"about_modal_awards"}>
            <div className={"about_modal_circle"}>
              <div className={"g_eyebrow_circle"} />
              <h2 className={"about_modal_heading u-text-style-h5"}>
                {"Awards"}
              </h2>
            </div>
            <div className={"about_clients_collection w-dyn-list"}>
              <div role={"list"} className={"about_clients_list w-dyn-items"}>
                <div role={"listitem"} className={"about_clients_item w-dyn-item"}>
                  <h2 className={"about_modal_heading u-text-style-h5"}>
                    {"Awwwards SOTD (x5)"}
                  </h2>
                </div>
                <div role={"listitem"} className={"about_clients_item w-dyn-item"}>
                  <h2 className={"about_modal_heading u-text-style-h5"}>
                    {"FWA SOTD (x5)"}
                  </h2>
                </div>
                <div role={"listitem"} className={"about_clients_item w-dyn-item"}>
                  <h2 className={"about_modal_heading u-text-style-h5"}>
                    {"CSSDA SOTD (x5)"}
                  </h2>
                </div>
                <div role={"listitem"} className={"about_clients_item w-dyn-item"}>
                  <h2 className={"about_modal_heading u-text-style-h5"}>
                    {"Awwwards Honorable Mention (x8)"}
                  </h2>
                </div>
                <div role={"listitem"} className={"about_clients_item w-dyn-item"}>
                  <h2 className={"about_modal_heading u-text-style-h5"}>
                    {"Awwwards Typography Honors (x2)"}
                  </h2>
                </div>
                <div role={"listitem"} className={"about_clients_item w-dyn-item"}>
                  <h2 className={"about_modal_heading u-text-style-h5"}>
                    {"Awwwards Independent of The Year Nominee (x1)"}
                  </h2>
                </div>
              </div>
            </div>
          </div>
          <div className={"about_modal_values"}>
            <div className={"about_modal_circle"}>
              <div className={"g_eyebrow_circle"} />
              <h2 className={"about_modal_heading u-text-style-h5"}>
                {"Our principles"}
              </h2>
            </div>
            <div className={"about_values_collection w-dyn-list"}>
              <div role={"list"} className={"about_values_list w-dyn-items"}>
                <div role={"listitem"} className={"about_values_item w-dyn-item"}>
                  <h2 className={"about_values_heading u-text-style-h5"}>
                    {"Outcomes first, taste second"}
                  </h2>
                  <p className={"about_values_p u-text-style-small"}>
                    {"Every creative decision we make is interrogated against one question: does this actually serve your growth?"}
                  </p>
                </div>
                <div role={"listitem"} className={"about_values_item w-dyn-item"}>
                  <h2 className={"about_values_heading u-text-style-h5"}>
                    {"All in or nothing"}
                  </h2>
                  <p className={"about_values_p u-text-style-small"}>
                    {"We take on fewer projects so we can give each one everything. When we commit to your brand, we're fully present, fully invested, fully responsible for the result."}
                  </p>
                </div>
                <div role={"listitem"} className={"about_values_item w-dyn-item"}>
                  <h2 className={"about_values_heading u-text-style-h5"}>
                    {"Human-first, always"}
                  </h2>
                  <p className={"about_values_p u-text-style-small"}>
                    {"Behind every brand is a person with a real story and real stakes. We never lose sight of that. The most powerful digital experiences are the ones that feel unmistakably human."}
                  </p>
                </div>
                <div role={"listitem"} className={"about_values_item w-dyn-item"}>
                  <h2 className={"about_values_heading u-text-style-h5"}>
                    {"Intention over speed"}
                  </h2>
                  <p className={"about_values_p u-text-style-small"}>
                    {"Rushed work compounds into regret. We move at the pace the work demands. Every layer earns its place before we move to the next."}
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
