// Generated by node scripts/generate-work-hero-data.mjs; do not edit.
export const WORK_HERO_SOURCE_SHA256 = 'd5b07e1e69514623f63c90b0b4439b434e9d62a0c48a1a5028457071939e95cc';

export interface WorkFilter {
  readonly target: string;
  readonly label: string;
}

export interface WorkService {
  readonly filterName: string;
  readonly label: string;
}

export interface WorkProject {
  readonly href: string | null;
  readonly title: string;
  readonly description: string;
  readonly year: string;
  readonly yearClassName: string;
  readonly imageSrc: string;
  readonly services: readonly WorkService[];
}

export interface WorkHeroData {
  readonly filterCss: string;
  readonly heading: string;
  readonly countPlaceholder: string;
  readonly eyebrow: string;
  readonly filters: readonly WorkFilter[];
  readonly projects: readonly WorkProject[];
}

export const WORK_HERO = {
  "filterCss": "\n\t/* Filter Button */\n[data-btn-default] .filter-btn {\n  transition: color 0.375s cubic-bezier(0.22, 1, 0.36, 1), background-color 0.375s cubic-bezier(0.22, 1, 0.36, 1);\n}\n\n.filter-btn[data-filter-status=\"active\"] {\n  background-color: #131313;\n  color: #EFEEEC;\n}\n\n/* Filter List Item */\n.hero_work_item[data-filter-status=\"active\"] {\n  transition: opacity 0.3s cubic-bezier(0.22, 1, 0.36, 1);\n  opacity: 1;\n  visibility: visible;\n  position: relative;\n}\n\n.hero_work_item[data-filter-status=\"transition-out\"] {\n  transition: opacity 0.25s cubic-bezier(0.22, 1, 0.36, 1);\n  opacity: 0;\n  visibility: visible;\n}\n\n.hero_work_item[data-filter-status=\"not-active\"] {\n  opacity: 0;\n  visibility: hidden; \n  position: absolute;\n}\n",
  "heading": "All success\u2028stories",
  "countPlaceholder": "##",
  "eyebrow": "Filter by service",
  "filters": [
    {
      "target": "all",
      "label": "All Projects"
    },
    {
      "target": "brand-strategy",
      "label": "Brand Strategy"
    },
    {
      "target": "visual-identity",
      "label": "Visual Identity"
    },
    {
      "target": "website-strategy",
      "label": "Website Strategy"
    },
    {
      "target": "website-design",
      "label": "Website Design"
    },
    {
      "target": "website-development",
      "label": "Website Development"
    }
  ],
  "projects": [
    {
      "href": "https://www.instagram.com/satusisisocialhouse/",
      "title": "Satu Sisi Social House",
      "description": "A strategic logo rebrand that gives Satu Sisi Social House a distinctive, memorable identity designed to strengthen recognition and connect with its audience.",
      "year": "2025",
      "yearClassName": "works_work_text u-text-style-small",
      "imageSrc": "https://cdn.prod.website-files.com/68b66e92dfdef050e1802fa7/68e36f423545f0f0d624de8c_image%206.avif",
      "services": [
        {
          "filterName": "brand-strategy",
          "label": "Brand Strategy"
        },
        {
          "filterName": "visual-identity",
          "label": "Visual Identity"
        }
      ]
    },
    {
      "href": "https://kehati-pltgucilegon.netlify.app/",
      "title": "PLN Indonesia Power",
      "description": "Website development for the PROPER KEHATI program at UBP Cilegon, presenting its biodiversity and environmental initiatives through a clear, accessible digital experience.",
      "year": "2025",
      "yearClassName": "works_work_text u-text-style-small",
      "imageSrc": "https://cdn.prod.website-files.com/68b66e92dfdef050e1802fa7/68e36fd385a3ac7e20eb2a7c_IMG_2674%201.avif",
      "services": [
        {
          "filterName": "website-strategy",
          "label": "Website Strategy"
        },
        {
          "filterName": "website-design",
          "label": "Website Design"
        },
        {
          "filterName": "website-development",
          "label": "Website Development"
        }
      ]
    },
    {
      "href": "https://otobi.id/",
      "title": "Otobi Auto Care",
      "description": "A custom e-commerce website that enables customers to explore products and complete transactions directly through a seamless, user-friendly online experience.",
      "year": "2025",
      "yearClassName": "works_work_text u-text-style-small",
      "imageSrc": "https://cdn.prod.website-files.com/68b66e92dfdef050e1802fa7/68e36f6a67c0bb840486917e_image-1.avif",
      "services": [
        {
          "filterName": "website-strategy",
          "label": "Website Strategy"
        },
        {
          "filterName": "website-design",
          "label": "Website Design"
        },
        {
          "filterName": "website-development",
          "label": "Website Development"
        }
      ]
    },
    {
      "href": null,
      "title": "Berkah Ryan",
      "description": "Website development and SEO improvements that increased search visibility and helped generate more crane rental enquiries.",
      "year": "2026",
      "yearClassName": "works_work_text u-text-style-small",
      "imageSrc": "https://cdn.prod.website-files.com/68b66e92dfdef050e1802fa7/6a10111e38d73116c8849278_Slik.avif",
      "services": [
        {
          "filterName": "website-development",
          "label": "Website Development"
        }
      ]
    },
    {
      "href": "https://www.goethe.de/",
      "title": "Goethe-Institut",
      "description": "Business process and user experience development focused on creating clearer workflows and a more intuitive digital journey for users.",
      "year": "2025",
      "yearClassName": "works_work_text u-text-style-small",
      "imageSrc": "https://cdn.prod.website-files.com/68b66e92dfdef050e1802fa7/68e36feaa84a7e56f526ef97_15_Mikeas_34513%201.avif",
      "services": [
        {
          "filterName": "website-strategy",
          "label": "Website Strategy"
        },
        {
          "filterName": "website-design",
          "label": "Website Design"
        }
      ]
    },
    {
      "href": null,
      "title": "Berdikari Raya",
      "description": "A results-driven SEO strategy that expanded its online reach and secured a top-ranking position on Google for its target market.",
      "year": "2026",
      "yearClassName": "works_work_text u-text-style-small",
      "imageSrc": "https://cdn.prod.website-files.com/68b66e92dfdef050e1802fa7/6a1010bcc3947445ad687f5d_Backhouse.avif",
      "services": [
        {
          "filterName": "website-strategy",
          "label": "Website Strategy"
        }
      ]
    },
    {
      "href": null,
      "title": "Disnaker Kota Cilegon",
      "description": "An ongoing website and worker card system development project designed to support the services of the Cilegon City Manpower Department.",
      "year": "",
      "yearClassName": "works_work_text u-text-style-small w-dyn-bind-empty",
      "imageSrc": "https://cdn.prod.website-files.com/68b66e92dfdef050e1802fa7/6a4cb0704d2b210c25519b1b_Squiggle.avif",
      "services": [
        {
          "filterName": "website-strategy",
          "label": "Website Strategy"
        },
        {
          "filterName": "website-design",
          "label": "Website Design"
        },
        {
          "filterName": "website-development",
          "label": "Website Development"
        }
      ]
    }
  ]
} as const satisfies WorkHeroData;
