// Generated by node scripts/generate-work-hero-data.mjs; do not edit.
export const WORK_HERO_SOURCE_SHA256 = '81287b1f394fc54563cd93f294eb19f98b5943f87a95497fddaef7d6c76c53e1';

export interface WorkFilter {
  readonly target: string;
  readonly label: string;
}

export interface WorkService {
  readonly filterName: string;
  readonly label: string;
}

export interface WorkProject {
  readonly href: string;
  readonly title: string;
  readonly description: string;
  readonly year: string;
  readonly yearClassName: string;
  readonly imageSrc: string;
  readonly services: readonly WorkService[];
}

export interface WorkHeroData {
  readonly filterCss: string;
  readonly heading: string;
  readonly countPlaceholder: string;
  readonly eyebrow: string;
  readonly filters: readonly WorkFilter[];
  readonly projects: readonly WorkProject[];
}

export const WORK_HERO = {
  "filterCss": "\n\t/* Filter Button */\n[data-btn-default] .filter-btn {\n  transition: color 0.375s cubic-bezier(0.22, 1, 0.36, 1), background-color 0.375s cubic-bezier(0.22, 1, 0.36, 1);\n}\n\n.filter-btn[data-filter-status=\"active\"] {\n  background-color: #131313;\n  color: #EFEEEC;\n}\n\n/* Filter List Item */\n.hero_work_item[data-filter-status=\"active\"] {\n  transition: opacity 0.3s cubic-bezier(0.22, 1, 0.36, 1);\n  opacity: 1;\n  visibility: visible;\n  position: relative;\n}\n\n.hero_work_item[data-filter-status=\"transition-out\"] {\n  transition: opacity 0.25s cubic-bezier(0.22, 1, 0.36, 1);\n  opacity: 0;\n  visibility: visible;\n}\n\n.hero_work_item[data-filter-status=\"not-active\"] {\n  opacity: 0;\n  visibility: hidden; \n  position: absolute;\n}\n",
  "heading": "All success\u2028stories",
  "countPlaceholder": "##",
  "eyebrow": "Filter by service",
  "filters": [
    {
      "target": "all",
      "label": "All Projects"
    },
    {
      "target": "brand-strategy",
      "label": "Brand Strategy"
    },
    {
      "target": "visual-identity",
      "label": "Visual Identity"
    },
    {
      "target": "website-strategy",
      "label": "Website Strategy"
    },
    {
      "target": "website-design",
      "label": "Website Design"
    },
    {
      "target": "website-development",
      "label": "Website Development"
    }
  ],
  "projects": [
    {
      "href": "https://www.oharchitecture.com.au/",
      "title": "OH Architecture",
      "description": "Brand refresh and website for a practice with a decade of crafting high-end homes for Australian families.",
      "year": "2025",
      "yearClassName": "works_work_text u-text-style-small",
      "imageSrc": "https://cdn.prod.website-files.com/68b66e92dfdef050e1802fa7/68e36f423545f0f0d624de8c_image%206.avif",
      "services": [
        {
          "filterName": "brand-strategy",
          "label": "Brand Strategy"
        },
        {
          "filterName": "website-strategy",
          "label": "Website Strategy"
        },
        {
          "filterName": "visual-identity",
          "label": "Visual Identity"
        },
        {
          "filterName": "website-design",
          "label": "Website Design"
        },
        {
          "filterName": "website-development",
          "label": "Website Development"
        }
      ]
    },
    {
      "href": "https://mammothmurals.com/",
      "title": "Mammoth Murals",
      "description": "Brand strategy, identity and website for an established mural agency with a decade of large-scale public art behind it.",
      "year": "2025",
      "yearClassName": "works_work_text u-text-style-small",
      "imageSrc": "https://cdn.prod.website-files.com/68b66e92dfdef050e1802fa7/68e36fd385a3ac7e20eb2a7c_IMG_2674%201.avif",
      "services": [
        {
          "filterName": "brand-strategy",
          "label": "Brand Strategy"
        },
        {
          "filterName": "website-strategy",
          "label": "Website Strategy"
        },
        {
          "filterName": "visual-identity",
          "label": "Visual Identity"
        },
        {
          "filterName": "website-design",
          "label": "Website Design"
        },
        {
          "filterName": "website-development",
          "label": "Website Development"
        }
      ]
    },
    {
      "href": "https://www.supersolid.agency/",
      "title": "Supersolid",
      "description": "Website for a 100% creative-owned Sydney agency built to merge commercial value with cultural impact.",
      "year": "2025",
      "yearClassName": "works_work_text u-text-style-small",
      "imageSrc": "https://cdn.prod.website-files.com/68b66e92dfdef050e1802fa7/68e36f6a67c0bb840486917e_image-1.avif",
      "services": [
        {
          "filterName": "website-design",
          "label": "Website Design"
        },
        {
          "filterName": "website-development",
          "label": "Website Development"
        },
        {
          "filterName": "3d-development",
          "label": "3D Development"
        }
      ]
    },
    {
      "href": "https://www.slik.com.au/",
      "title": "SLIK",
      "description": "Website for an Australian activation agency pushing creativity further for some of the country's most ambitious brands.",
      "year": "2026",
      "yearClassName": "works_work_text u-text-style-small",
      "imageSrc": "https://cdn.prod.website-files.com/68b66e92dfdef050e1802fa7/6a10111e38d73116c8849278_Slik.avif",
      "services": [
        {
          "filterName": "website-development",
          "label": "Website Development"
        },
        {
          "filterName": "3d-development",
          "label": "3D Development"
        }
      ]
    },
    {
      "href": "https://www.hiss.sydney/",
      "title": "HISS (University of Sydney)",
      "description": "Brand identity and website for a University of Sydney initiative challenging the norms of queer education on a global stage.",
      "year": "2025",
      "yearClassName": "works_work_text u-text-style-small",
      "imageSrc": "https://cdn.prod.website-files.com/68b66e92dfdef050e1802fa7/68e36feaa84a7e56f526ef97_15_Mikeas_34513%201.avif",
      "services": [
        {
          "filterName": "visual-identity",
          "label": "Visual Identity"
        },
        {
          "filterName": "website-design",
          "label": "Website Design"
        },
        {
          "filterName": "website-development",
          "label": "Website Development"
        }
      ]
    },
    {
      "href": "https://www.backhouse.com/",
      "title": "Backhouse",
      "description": "Website for an embedded production partner behind campaigns for Netflix, A24, HBO, Apple and Google.",
      "year": "2026",
      "yearClassName": "works_work_text u-text-style-small",
      "imageSrc": "https://cdn.prod.website-files.com/68b66e92dfdef050e1802fa7/6a1010bcc3947445ad687f5d_Backhouse.avif",
      "services": [
        {
          "filterName": "website-design",
          "label": "Website Design"
        },
        {
          "filterName": "website-development",
          "label": "Website Development"
        },
        {
          "filterName": "3d-development",
          "label": "3D Development"
        }
      ]
    },
    {
      "href": "https://www.squiggle.sydney/",
      "title": "Squiggle (University of Sydney)",
      "description": "Website for a social enterprise transforming interpersonal experiences through gamified, research-based education.",
      "year": "",
      "yearClassName": "works_work_text u-text-style-small w-dyn-bind-empty",
      "imageSrc": "https://cdn.prod.website-files.com/68b66e92dfdef050e1802fa7/6a4cb0704d2b210c25519b1b_Squiggle.avif",
      "services": [
        {
          "filterName": "website-strategy",
          "label": "Website Strategy"
        },
        {
          "filterName": "website-design",
          "label": "Website Design"
        },
        {
          "filterName": "website-development",
          "label": "Website Development"
        }
      ]
    }
  ]
} as const satisfies WorkHeroData;
