// Generated by node scripts/generate-cursor-data.mjs; do not edit.
export const CURSOR_SOURCE_SHA256 = {
  "/": "1c0c98897b459caee8f49dd7c82f1357104495234ac17ee61a02f8db7cf7003d",
  "/work": "d5b07e1e69514623f63c90b0b4439b434e9d62a0c48a1a5028457071939e95cc",
  "/projects/backhouse": "561410cd4a79ab5df64425826388c99e1e2de3d32209e5898971d9796ef65c01",
  "/projects/hiss-university-of-sydney": "561410cd4a79ab5df64425826388c99e1e2de3d32209e5898971d9796ef65c01",
  "/projects/mammoth-murals": "561410cd4a79ab5df64425826388c99e1e2de3d32209e5898971d9796ef65c01",
  "/projects/oh-architecture": "561410cd4a79ab5df64425826388c99e1e2de3d32209e5898971d9796ef65c01",
  "/projects/slik": "561410cd4a79ab5df64425826388c99e1e2de3d32209e5898971d9796ef65c01",
  "/projects/squiggle-university-of-sydney": "561410cd4a79ab5df64425826388c99e1e2de3d32209e5898971d9796ef65c01",
  "/projects/supersolid": "561410cd4a79ab5df64425826388c99e1e2de3d32209e5898971d9796ef65c01"
} as const;

export const SHARED_CURSOR = {
  "home": {
    "css": "\\n  @media (hover: hover) and (pointer: fine) {\\n\\n\\n  /* \u2500\u2500 Bubble base \u2500\u2500 */\\n  [data-cursor] .cursor-bubble {\\n    clip-path: inset(0% 100% 0% 0% round 6px);\\n    opacity: 0;\\n    transform: translateX(0%) scale(0.92) rotate(0.001deg);\\n    transition:\\n      clip-path 0.45s cubic-bezier(0.16, 1, 0.3, 1),\\n      opacity 0.2s cubic-bezier(0.16, 1, 0.3, 1),\\n      transform 0.45s cubic-bezier(0.16, 1, 0.3, 1);\\n  }\\n\\n  /* \u2500\u2500 Active: wipe open left \u2192 right \u2500\u2500 */\\n  [data-cursor='active'] .cursor-bubble {\\n    clip-path: inset(0% 0% 0% 0% round 6px);\\n    opacity: 1;\\n    transform: translateX(0%) scale(1) rotate(0.001deg);\\n  }\\n\\n  /* \u2500\u2500 Active edge: flip to left side \u2500\u2500 */\\n  [data-cursor='active-edge'] .cursor-bubble {\\n    clip-path: inset(0% 0% 0% 0% round 6px);\\n    opacity: 1;\\n    transform: translateX(-100%) scale(1) rotate(0.001deg);\\n  }\\n\\n  /* \u2500\u2500 Content inside bubble \u2500\u2500 */\\n  [data-cursor] .cursor-bubble [data-cursor-text-target] {\\n    opacity: 0;\\n    transform: translateY(4px);\\n    transition:\\n      opacity 0.2s cubic-bezier(0.16, 1, 0.3, 1),\\n      transform 0.2s cubic-bezier(0.16, 1, 0.3, 1);\\n  }\\n\\n  [data-cursor='active'] .cursor-bubble [data-cursor-text-target],\\n  [data-cursor='active-edge'] .cursor-bubble [data-cursor-text-target] {\\n    opacity: 1;\\n    transform: translateY(0);\\n  }\\n}\\n\\n@media (hover: none) and (pointer: coarse) {\\n  .cursor_wrap {\\n    display: none;\\n  }\\n}\\n"
  },
  "work": {
    "css": "\n  @media (hover: hover) and (pointer: fine) {\n\n\n  /* \u2500\u2500 Bubble base \u2500\u2500 */\n  [data-cursor] .cursor-bubble {\n    clip-path: inset(0% 100% 0% 0% round 6px);\n    opacity: 0;\n    transform: translateX(0%) scale(0.92) rotate(0.001deg);\n    transition:\n      clip-path 0.45s cubic-bezier(0.16, 1, 0.3, 1),\n      opacity 0.2s cubic-bezier(0.16, 1, 0.3, 1),\n      transform 0.45s cubic-bezier(0.16, 1, 0.3, 1);\n  }\n\n  /* \u2500\u2500 Active: wipe open left \u2192 right \u2500\u2500 */\n  [data-cursor='active'] .cursor-bubble {\n    clip-path: inset(0% 0% 0% 0% round 6px);\n    opacity: 1;\n    transform: translateX(0%) scale(1) rotate(0.001deg);\n  }\n\n  /* \u2500\u2500 Active edge: flip to left side \u2500\u2500 */\n  [data-cursor='active-edge'] .cursor-bubble {\n    clip-path: inset(0% 0% 0% 0% round 6px);\n    opacity: 1;\n    transform: translateX(-100%) scale(1) rotate(0.001deg);\n  }\n\n  /* \u2500\u2500 Content inside bubble \u2500\u2500 */\n  [data-cursor] .cursor-bubble [data-cursor-text-target] {\n    opacity: 0;\n    transform: translateY(4px);\n    transition:\n      opacity 0.2s cubic-bezier(0.16, 1, 0.3, 1),\n      transform 0.2s cubic-bezier(0.16, 1, 0.3, 1);\n  }\n\n  [data-cursor='active'] .cursor-bubble [data-cursor-text-target],\n  [data-cursor='active-edge'] .cursor-bubble [data-cursor-text-target] {\n    opacity: 1;\n    transform: translateY(0);\n  }\n}\n\n@media (hover: none) and (pointer: coarse) {\n  .cursor_wrap {\n    display: none;\n  }\n}\n"
  }
} as const;

export type CursorVariant = keyof typeof SHARED_CURSOR;
