// Generated by node scripts/generate-navbar-data.mjs; do not edit.
export const NAVBAR_SOURCE_SHA256 = {
  "home": "1c0c98897b459caee8f49dd7c82f1357104495234ac17ee61a02f8db7cf7003d",
  "work": "d5b07e1e69514623f63c90b0b4439b434e9d62a0c48a1a5028457071939e95cc"
} as const;

export const SHARED_NAVBAR = {
  "home": {
    "homeHref": "#",
    "aboutSoon": "(SOON)",
    "workClassName": "navbar_link w-inline-block",
    "workAriaCurrent": null,
    "servicesHref": "#services",
    "processHref": "#process",
    "brand": {
      "image": {
        "src": "/arxenovasocial-logo.webp",
        "alt": "Arxenova Social",
        "className": "navbar_home_svg",
        "style": {
          "height": "auto",
          "maxHeight": "42px",
          "width": "auto",
          "objectFit": "contain",
          "display": "block"
        }
      },
      "text": {
        "className": "navbar_brand_text",
        "style": {
          "fontWeight": "800",
          "fontSize": "16px",
          "letterSpacing": "0.12em",
          "textTransform": "uppercase",
          "marginLeft": "10px",
          "color": "inherit",
          "display": "inline-block",
          "verticalAlign": "middle"
        },
        "content": "ARXENOVASOCIAL"
      }
    }
  },
  "work": {
    "homeHref": "/",
    "aboutSoon": "",
    "workClassName": "navbar_link w-inline-block w--current",
    "workAriaCurrent": "page",
    "servicesHref": "https://bymonolog.com/#services",
    "processHref": "https://bymonolog.com/#process",
    "brand": {
      "image": {
        "src": "/arxenovasocial-logo.webp",
        "alt": "Arxenova Social",
        "className": "navbar_home_svg",
        "style": {
          "height": "auto",
          "maxHeight": "42px",
          "width": "auto",
          "objectFit": "contain",
          "display": "block"
        }
      },
      "text": {
        "className": "navbar_brand_text",
        "style": {
          "fontWeight": "800",
          "fontSize": "16px",
          "letterSpacing": "0.12em",
          "textTransform": "uppercase",
          "marginLeft": "10px",
          "color": "inherit",
          "display": "inline-block",
          "verticalAlign": "middle"
        },
        "content": "ARXENOVASOCIAL"
      }
    }
  }
} as const;

export type NavbarVariant = keyof typeof SHARED_NAVBAR;
