// Generated by node scripts/generate-about-data.mjs; do not edit.
export const ABOUT_SOURCE_SHA256 = {
  "/": "1c0c98897b459caee8f49dd7c82f1357104495234ac17ee61a02f8db7cf7003d",
  "/work": "81287b1f394fc54563cd93f294eb19f98b5943f87a95497fddaef7d6c76c53e1"
} as const;

export const SHARED_ABOUT = {
  "home": {
    "css": "\\n\\n.about_overlay_close, .menu_overlay_close {\\n\\topacity: 0;\\n  visiblity: hidden;\\n}\\n\\n.about_modal_contain {\\n  -webkit-overflow-scrolling: touch;\\n}\\n\\n/* .about_modal_wrap {\\n  transform: translateX(100%)\\n} */\\n\\n"
  },
  "work": {
    "css": "\n\n.about_overlay_close, .menu_overlay_close {\n\topacity: 0;\n  visiblity: hidden;\n}\n\n.about_modal_contain {\n  -webkit-overflow-scrolling: touch;\n}\n\n/* .about_modal_wrap {\n  transform: translateX(100%)\n} */\n\n"
  }
} as const;

export type AboutVariant = keyof typeof SHARED_ABOUT;

export const ABOUT_BRAILLE_PATHS = [
  {
    "d": "M14 1.5C14 2.32843 13.3284 3 12.5 3C11.6716 3 11 2.32843 11 1.5C11 0.671573 11.6716 0 12.5 0C13.3284 0 14 0.671573 14 1.5Z",
    "fill": "currentColor"
  },
  {
    "d": "M25 1.5C25 2.32843 24.3284 3 23.5 3C22.6716 3 22 2.32843 22 1.5C22 0.671573 22.6716 0 23.5 0C24.3284 0 25 0.671573 25 1.5Z",
    "fill": "currentColor"
  },
  {
    "d": "M7 1.5C7 2.32843 6.32843 3 5.5 3C4.67157 3 4 2.32843 4 1.5C4 0.671573 4.67157 0 5.5 0C6.32843 0 7 0.671573 7 1.5Z",
    "fill": "currentColor"
  },
  {
    "d": "M18 1.5C18 2.32843 17.3284 3 16.5 3C15.6716 3 15 2.32843 15 1.5C15 0.671573 15.6716 0 16.5 0C17.3284 0 18 0.671573 18 1.5Z",
    "fill": "currentColor"
  },
  {
    "d": "M18 5.5C18 6.32843 17.3284 7 16.5 7C15.6716 7 15 6.32843 15 5.5C15 4.67157 15.6716 4 16.5 4C17.3284 4 18 4.67157 18 5.5Z",
    "fill": "currentColor"
  },
  {
    "d": "M29 5.5C29 6.32843 28.3284 7 27.5 7C26.6716 7 26 6.32843 26 5.5C26 4.67157 26.6716 4 27.5 4C28.3284 4 29 4.67157 29 5.5Z",
    "fill": "currentColor"
  },
  {
    "d": "M25 5.5C25 6.32843 24.3284 7 23.5 7C22.6716 7 22 6.32843 22 5.5C22 4.67157 22.6716 4 23.5 4C24.3284 4 25 4.67157 25 5.5Z",
    "fill": "currentColor"
  },
  {
    "d": "M3 9.5C3 10.3284 2.32843 11 1.5 11C0.671573 11 0 10.3284 0 9.5C0 8.67157 0.671573 8 1.5 8C2.32843 8 3 8.67157 3 9.5Z",
    "fill": "currentColor"
  },
  {
    "d": "M29 9.5C29 10.3284 28.3284 11 27.5 11C26.6716 11 26 10.3284 26 9.5C26 8.67157 26.6716 8 27.5 8C28.3284 8 29 8.67157 29 9.5Z",
    "fill": "currentColor"
  }
] as const;
